Add validation
mineiros-io/terraform-google-folder-iam pull request #13
Opened 2022-01-04 03:14 UTC by soerenmartius

2022-01-04 11:02 UTC, mariux requested changes

2022-01-04 11:02 UTC, mariux commented on variables.tf
> +    condition     = alltrue([for m in var.members : can(regex("^(user|serviceAccount|group|domain):(.+)", m))])
```suggestion
    condition     = alltrue([for m in var.members : can(regex("^(user|serviceAccount|group|domain):", m))])
```

2022-01-04 20:49 UTC, soerenmartius commented on variables.tf
> +    condition     = alltrue([for m in var.members : can(regex("^(user|serviceAccount|group|domain):(.+)", m))])
resolved in 76e41f03

2022-01-05 10:35 UTC, kassianh approved these changes
lgtm

2022-01-10 14:31 UTC, mariux approved these changes
lgtm

2022-01-10 14:38 UTC, merged