feat: add audit logs
mineiros-io/terraform-google-folder-iam pull request #16
Opened 2022-03-18 12:08 UTC by thiesen

2022-03-18 14:06 UTC, soerenmartius requested changes

2022-03-18 14:06 UTC, soerenmartius commented on README.tfdoc.hcl
> +            }]
```suggestion
            # Enable full audit log coverage for all services
            audit_configs = [
                {
                    service = "allServices"
                    configs = [
                        {
                            log_type = "DATA_READ"
                        },
                        {
                            log_type = "DATA_WRITE"
                        },
                        {
                            log_type = "ADMIN_READ"
                        },
                        {
                            log_type = "ADMIN_WRITE"
                        },
                    ]
                }
            ]
```

2022-03-18 14:06 UTC, soerenmartius commented on README.tfdoc.hcl
> +            }]
let's add a more comprehensive example for this case

2022-03-18 15:10 UTC, 1fawadshah commented on README.tfdoc.hcl
> +            attribute "exempted_users" {
It should be "exempted_members"

2022-03-18 16:04 UTC, soerenmartius requested changes
Could you add the changes to the `CHANGELOG.md` also please? thanks!

2022-03-20 20:14 UTC, mariux requested changes

2022-03-20 20:14 UTC, mariux commented on README.tfdoc.hcl
> +          type = object(audit_log)
```suggestion
          type = object(audit_config)
```

2022-03-22 22:53 UTC, kassianh approved these changes
lgtm!

2022-03-23 12:43 UTC, thiesen commented
hey @soerenmartius - I just pushed the changelog changes - please advise if the text is good enough. 

sorry for the delay - I somehow missed the request for updating it; thanks @kassianh for pointing it out

2022-03-23 14:38 UTC, soerenmartius submitted a review, later dismissed
lgtm! @mariux are we good to go here?

2022-03-28 09:30 UTC, mariux approved these changes
lgtm

2022-03-28 09:30 UTC, merged