doc: update readme
mineiros-io/terraform-google-folder-iam pull request #9
Opened 2021-11-02 08:18 UTC by samen93

2021-11-03 17:33 UTC, mariux requested changes

2021-11-03 17:33 UTC, mariux commented on README.md
> +- `google_iam_policy`
this has been removed in several PRs ...please adjust...

2021-11-04 16:22 UTC, mariux requested changes

2021-11-04 16:22 UTC, mariux commented on variables.tf
> +
makes role optional?

2021-11-06 14:10 UTC, samen93 commented on README.md
> +- `google_iam_policy`
@mariux no one informed me that they are removed, i add them in all readme files!

2021-11-08 14:52 UTC, mariux approved these changes

2021-11-08 14:52 UTC, merged